services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    container_name: ${CONTAINER_NAME_APACHE}
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - "./:/usr/local/apache2/htdocs"
    networks:
      - default

networks:
  default:
    driver: bridge