services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: ${CONTAINER_NAME_MAILPIT}
    ports:
      - "${MAILPIT_PORT}:8025"
      - "${MAILPIT_SMTP_PORT}:1025"
    networks:
      - mtdocker-network
