services:
  apache:
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    container_name: ${CONTAINER_NAME_OLLAMA}
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ${MTDOCKER_PATH}/ollama:/root/.ollama
    networks:
      - mtdocker-network
