services:
  apache:
    build:
      context: ${MTDOCKER_PATH}
      dockerfile: html/Dockerfile
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
    container_name: ${CONTAINER_NAME_APACHE}
    ports:
      - "${APACHE_PORT}:80"
    volumes:
      - ${PROJECT_PATH}:/usr/local/apache2/htdocs
    networks:
      - mtdocker-network

networks:
  mtdocker-network:
    driver: bridge
