<?php

namespace MulerTech\DockerDev;

/**
 * Class Symfony.
 */
class Symfony
{
    private Composer $composer;

    public function __construct(Composer $composer)
    {
        $this->composer = $composer;
    }

    public function configureDoctrine(): void
    {
        $projectDir = $this->composer->getProjectDir();
        $doctrinePath = $projectDir.'/config/packages/doctrine.yaml';

        if (!file_exists($doctrinePath)) {
            return; // Skip if doctrine.yaml doesn't exist
        }

        $doctrineContent = (string) file_get_contents($doctrinePath);

        $updatedContent = $this->applyDoctrineDockerConfig($doctrineContent);
        $updatedContent = $this->applyDoctrineServerVersion($updatedContent);

        if ($updatedContent !== $doctrineContent) {
            file_put_contents($doctrinePath, $updatedContent);
            echo "Updated config/packages/doctrine.yaml for Docker environment\n";
        }
    }

    private function applyDoctrineDockerConfig(string $content): string
    {
        // Check if already modified (avoid duplicate modifications)
        if (str_contains($content, '# Modified by mulertech/docker-dev package for Docker environment')) {
            return $content;
        }

        // Replace the DATABASE_URL configuration with flexible fallback configuration
        $oldConfig = "url: '%env(resolve:DATABASE_URL)%'";
        $newConfig = "# Modified by mulertech/docker-dev package for Docker environment
        host: '%env(default::DATABASE_HOST)%'
        port: '%env(default::DATABASE_PORT)%'
        dbname: '%env(default::DATABASE_NAME)%'
        user: '%env(default::DATABASE_USER)%'
        password: '%env(trim:file:DATABASE_PASSWORD_FILE)%'
        driver: 'pdo_pgsql'";

        return str_replace($oldConfig, $newConfig, $content);
    }

    private function applyDoctrineServerVersion(string $content): string
    {
        $target = "server_version: '%env(default::DATABASE_SERVER_VERSION)%'";

        if (str_contains($content, $target)) {
            return $content;
        }

        return (string) preg_replace('/^(\h*)#?\h*server_version:[^\r\n]*/m', '$1'.$target, $content, 1);
    }

    public function configureDoctrineTest(): void
    {
        $projectDir = $this->composer->getProjectDir();
        $doctrinePath = $projectDir.'/config/packages/doctrine.yaml';

        if (!file_exists($doctrinePath)) {
            return;
        }

        $doctrineContent = (string) file_get_contents($doctrinePath);

        if (str_contains($doctrineContent, "password: '%env(DATABASE_PASSWORD)%'")) {
            return;
        }

        $search = "when@test:\n    doctrine:\n        dbal:\n";

        if (str_contains($doctrineContent, $search)) {
            $updatedContent = str_replace(
                $search,
                $search."            password: '%env(DATABASE_PASSWORD)%'\n",
                $doctrineContent,
            );
            file_put_contents($doctrinePath, $updatedContent);

            return;
        }

        if (!str_contains($doctrineContent, 'when@test:')) {
            $doctrineContent .= "\nwhen@test:\n    doctrine:\n        dbal:\n            password: '%env(DATABASE_PASSWORD)%'\n";
            file_put_contents($doctrinePath, $doctrineContent);
        }
    }

    /** @param array<string> $modules */
    public function generateTestEnvLocal(array $modules, string $mtdockerEnvPath): void
    {
        $projectDir = $this->composer->getProjectDir();
        $envTestLocalPath = $projectDir.DIRECTORY_SEPARATOR.'.env.test.local';

        $envContent = (string) file_get_contents($mtdockerEnvPath);

        $dbPort = '';
        $dbDriver = '';

        if (preg_match('/^POSTGRES_PORT=(\d+)$/m', $envContent, $matches)) {
            $dbPort = $matches[1];
            $dbDriver = 'pdo_pgsql';
        } elseif (preg_match('/^MYSQL_PORT=(\d+)$/m', $envContent, $matches)) {
            $dbPort = $matches[1];
            $dbDriver = 'pdo_mysql';
        }

        if ('' === $dbPort) {
            return;
        }

        $lines = [
            '# Generated by mulertech/docker-dev — regenerated on each mtdocker init',
            'DATABASE_HOST=host.docker.internal',
            "DATABASE_PORT=$dbPort",
            'DATABASE_NAME=db',
            'DATABASE_USER=user',
            'DATABASE_PASSWORD=password',
            "DATABASE_DRIVER=$dbDriver",
        ];

        if (preg_match('/^DATABASE_SERVER_VERSION=(.+)$/m', $envContent, $matches)) {
            $lines[] = 'DATABASE_SERVER_VERSION='.$matches[1];
        }

        file_put_contents($envTestLocalPath, implode("\n", $lines)."\n");
    }

    public function configureMailer(): void
    {
        $projectDir = $this->composer->getProjectDir();
        $mailerPath = $projectDir.'/config/packages/mailer.yaml';

        if (!file_exists($mailerPath)) {
            return;
        }

        $mailerContent = (string) file_get_contents($mailerPath);

        if (!str_contains($mailerContent, '# Modified by mulertech/docker-dev package for Docker environment')) {
            $oldConfig = "dsn: '%env(MAILER_DSN)%'";
            $newConfig = "# Modified by mulertech/docker-dev package for Docker environment
            dsn: '%env(trim:file:MAILER_DSN_FILE)%'";

            $updatedContent = str_replace($oldConfig, $newConfig, $mailerContent);

            if ($updatedContent !== $mailerContent) {
                $mailerContent = $updatedContent;
                file_put_contents($mailerPath, $mailerContent);
                echo "Updated config/packages/mailer.yaml for Docker environment\n";
            }
        }

        $this->configureMailerTest($mailerPath, $mailerContent);
    }

    private function configureMailerTest(string $mailerPath, string $mailerContent): void
    {
        if (str_contains($mailerContent, "dsn: '%env(MAILER_DSN)%'")) {
            return;
        }

        if (str_contains($mailerContent, 'when@test:')) {
            return;
        }

        $mailerContent .= "\nwhen@test:\n    framework:\n        mailer:\n            dsn: '%env(MAILER_DSN)%'\n";
        file_put_contents($mailerPath, $mailerContent);
    }
}
