<?php

namespace MulerTech\DockerDev;

/**
 * Class Symfony.
 */
class Symfony
{
    private Composer $composer;

    public function __construct(Composer $composer)
    {
        $this->composer = $composer;
    }

    public function configureDoctrine(): void
    {
        $projectDir = $this->composer->getProjectDir();
        $doctrinePath = $projectDir.'/config/packages/doctrine.yaml';

        if (!file_exists($doctrinePath)) {
            return; // Skip if doctrine.yaml doesn't exist
        }

        $doctrineContent = (string) file_get_contents($doctrinePath);

        $updatedContent = $this->applyDoctrineDockerConfig($doctrineContent);
        $updatedContent = $this->applyDoctrineServerVersion($updatedContent);

        if ($updatedContent !== $doctrineContent) {
            file_put_contents($doctrinePath, $updatedContent);
            echo "Updated config/packages/doctrine.yaml for Docker environment\n";
        }
    }

    private function applyDoctrineDockerConfig(string $content): string
    {
        // Check if already modified (avoid duplicate modifications)
        if (str_contains($content, '# Modified by mulertech/docker-dev package for Docker environment')) {
            return $content;
        }

        // Replace the DATABASE_URL configuration with flexible fallback configuration
        $oldConfig = "url: '%env(resolve:DATABASE_URL)%'";
        $newConfig = "# Modified by mulertech/docker-dev package for Docker environment
        host: '%env(default::DATABASE_HOST)%'
        port: '%env(default::DATABASE_PORT)%'
        dbname: '%env(default::DATABASE_NAME)%'
        user: '%env(default::DATABASE_USER)%'
        password: '%env(trim:file:DATABASE_PASSWORD_FILE)%'
        driver: 'pdo_pgsql'";

        return str_replace($oldConfig, $newConfig, $content);
    }

    private function applyDoctrineServerVersion(string $content): string
    {
        $target = "server_version: '%env(default::DATABASE_SERVER_VERSION)%'";

        if (str_contains($content, $target)) {
            return $content;
        }

        return (string) preg_replace('/^(\h*)#?\h*server_version:[^\r\n]*/m', '$1'.$target, $content, 1);
    }

    public function configureDoctrineTest(): void
    {
        $projectDir = $this->composer->getProjectDir();
        $doctrinePath = $projectDir.'/config/packages/doctrine.yaml';

        if (!file_exists($doctrinePath)) {
            return;
        }

        $doctrineContent = (string) file_get_contents($doctrinePath);

        if (str_contains($doctrineContent, "password: '%env(DATABASE_PASSWORD)%'")) {
            return;
        }

        $search = "when@test:\n    doctrine:\n        dbal:\n";

        if (str_contains($doctrineContent, $search)) {
            $updatedContent = str_replace(
                $search,
                $search."            password: '%env(DATABASE_PASSWORD)%'\n",
                $doctrineContent,
            );
            file_put_contents($doctrinePath, $updatedContent);

            return;
        }

        if (!str_contains($doctrineContent, 'when@test:')) {
            $doctrineContent .= "\nwhen@test:\n    doctrine:\n        dbal:\n            password: '%env(DATABASE_PASSWORD)%'\n";
            file_put_contents($doctrinePath, $doctrineContent);
        }
    }

    /** @param array<string> $modules */
    public function generateTestEnvLocal(array $modules, string $mtdockerEnvPath): void
    {
        $projectDir = $this->composer->getProjectDir();
        $envTestLocalPath = $projectDir.DIRECTORY_SEPARATOR.'.env.test.local';

        $envContent = (string) file_get_contents($mtdockerEnvPath);

        $dbPort = '';
        $dbDriver = '';

        if (preg_match('/^POSTGRES_PORT=(\d+)$/m', $envContent, $matches)) {
            $dbPort = $matches[1];
            $dbDriver = 'pdo_pgsql';
        } elseif (preg_match('/^MYSQL_PORT=(\d+)$/m', $envContent, $matches)) {
            $dbPort = $matches[1];
            $dbDriver = 'pdo_mysql';
        }

        if ('' === $dbPort) {
            return;
        }

        $lines = [
            '# Generated by mulertech/docker-dev — regenerated on each mtdocker init',
            'DATABASE_HOST=host.docker.internal',
            "DATABASE_PORT=$dbPort",
            'DATABASE_NAME=db',
            'DATABASE_USER=user',
            'DATABASE_PASSWORD=password',
            "DATABASE_DRIVER=$dbDriver",
        ];

        if (preg_match('/^DATABASE_SERVER_VERSION=(.+)$/m', $envContent, $matches)) {
            $lines[] = 'DATABASE_SERVER_VERSION='.$matches[1];
        }

        file_put_contents($envTestLocalPath, implode("\n", $lines)."\n");
    }

    public function configureMailer(): void
    {
        $projectDir = $this->composer->getProjectDir();
        $mailerPath = $projectDir.'/config/packages/mailer.yaml';

        if (!file_exists($mailerPath)) {
            return;
        }

        $mailerContent = (string) file_get_contents($mailerPath);

        if (!str_contains($mailerContent, '# Modified by mulertech/docker-dev package for Docker environment')) {
            $oldConfig = "dsn: '%env(MAILER_DSN)%'";
            $newConfig = "# Modified by mulertech/docker-dev package for Docker environment
            dsn: '%env(trim:file:MAILER_DSN_FILE)%'";

            $updatedContent = str_replace($oldConfig, $newConfig, $mailerContent);

            if ($updatedContent !== $mailerContent) {
                $mailerContent = $updatedContent;
                file_put_contents($mailerPath, $mailerContent);
                echo "Updated config/packages/mailer.yaml for Docker environment\n";
            }
        }

        $this->configureMailerTest($mailerPath, $mailerContent);
    }

    /**
     * Les trois configure* reposent sur le remplacement d'une chaîne exacte, celle que
     * produisent les recettes Symfony. Si une recette change cette ligne, ou si le projet
     * l'a éditée à la main, le remplacement ne trouve rien — et ne dit rien.
     *
     * Le silence est le vrai risque : la production ne met plus aucune de ces trois valeurs
     * dans le .env, puisque celui-ci est copié dans l'image. Une clé restée branchée sur
     * l'environnement n'échouerait donc qu'au déploiement, loin de sa cause.
     */
    public function verifyConfiguration(): void
    {
        $expected = [
            'config/packages/doctrine.yaml' => "password: '%env(trim:file:DATABASE_PASSWORD_FILE)%'",
            'config/packages/mailer.yaml' => "dsn: '%env(trim:file:MAILER_DSN_FILE)%'",
            'config/packages/framework.yaml' => "secret: '%env(trim:file:APP_SECRET_FILE)%'",
        ];

        $projectDir = $this->composer->getProjectDir();
        $missing = [];

        foreach ($expected as $relativePath => $line) {
            $path = $projectDir.DIRECTORY_SEPARATOR.$relativePath;

            // Un fichier absent signifie que le composant n'est pas installé : rien à vérifier.
            if (!file_exists($path)) {
                continue;
            }

            if (!str_contains((string) file_get_contents($path), $line)) {
                $missing[$relativePath] = $line;
            }
        }

        if ([] === $missing) {
            return;
        }

        echo "\n⚠️  These secrets are not wired to a mounted file:\n";
        foreach ($missing as $relativePath => $line) {
            echo '   - '.$relativePath.' — expected: '.$line."\n";
        }
        echo "   Production mounts them as Docker secrets and keeps no value in .env, which is\n";
        echo "   copied into the image. A key still read from the environment fails at deployment.\n";
    }

    /**
     * APP_SECRET signe les jetons CSRF, les cookies remember-me et les URI signées. Le lire
     * depuis un fichier plutôt que depuis le .env évite qu'il finisse dans une couche d'image :
     * en production le .env de déploiement est copié dans l'image comme .env de Symfony, et une
     * couche survit à toute correction ultérieure du fichier.
     */
    public function configureFramework(): void
    {
        $projectDir = $this->composer->getProjectDir();
        $frameworkPath = $projectDir.'/config/packages/framework.yaml';

        if (!file_exists($frameworkPath)) {
            return;
        }

        $frameworkContent = (string) file_get_contents($frameworkPath);

        if (!str_contains($frameworkContent, '# Modified by mulertech/docker-dev package for Docker environment')) {
            $oldConfig = "secret: '%env(APP_SECRET)%'";
            $newConfig = "# Modified by mulertech/docker-dev package for Docker environment
    secret: '%env(trim:file:APP_SECRET_FILE)%'";

            $updatedContent = str_replace($oldConfig, $newConfig, $frameworkContent);

            if ($updatedContent !== $frameworkContent) {
                $frameworkContent = $updatedContent;
                file_put_contents($frameworkPath, $frameworkContent);
                echo "Updated config/packages/framework.yaml for Docker environment\n";
            }
        }

        $this->configureFrameworkTest($frameworkPath, $frameworkContent);
    }

    /**
     * Les variables de type fichier ne sont pas disponibles quand les tests tournent hors de
     * Docker Compose — PHPStorm, par exemple. L'environnement de test lit donc APP_SECRET
     * directement, comme le font déjà doctrine.yaml et mailer.yaml.
     *
     * La présence de la valeur d'environnement sert de garde : tant que la configuration de
     * base n'a pas été convertie, il n'y a rien à surcharger.
     */
    private function configureFrameworkTest(string $frameworkPath, string $frameworkContent): void
    {
        if (str_contains($frameworkContent, "secret: '%env(APP_SECRET)%'")) {
            return;
        }

        $search = "when@test:\n    framework:\n";

        if (str_contains($frameworkContent, $search)) {
            $updatedContent = str_replace(
                $search,
                $search."        secret: '%env(APP_SECRET)%'\n",
                $frameworkContent,
            );
            file_put_contents($frameworkPath, $updatedContent);

            return;
        }

        $frameworkContent .= "\nwhen@test:\n    framework:\n        secret: '%env(APP_SECRET)%'\n";
        file_put_contents($frameworkPath, $frameworkContent);
    }

    private function configureMailerTest(string $mailerPath, string $mailerContent): void
    {
        if (str_contains($mailerContent, "dsn: '%env(MAILER_DSN)%'")) {
            return;
        }

        if (str_contains($mailerContent, 'when@test:')) {
            return;
        }

        $mailerContent .= "\nwhen@test:\n    framework:\n        mailer:\n            dsn: '%env(MAILER_DSN)%'\n";
        file_put_contents($mailerPath, $mailerContent);
    }
}
